### ISSUE TITLE
Order of role resources not guaranteed in the resulting DSL

### ISSUE THREAD

**Issue by llange** [winebarrel/miam#15]
I'm keeping the generated DSL under source control for auditing needs.

From time to time, there are some changes in the parameter orders for the roles - changes which will NOT result in any modification on the AWS side ; but still causes the files to be different.

Example:
*  I have generated a DSL with the following command: 
`AWS_REGION=eu-west-1 miam --export --split`

* I've committed the generated files to source control

* After a while (and external modifications on the AWS account), I re-export and regenerate a DSL with the same command:
`AWS_REGION=eu-west-1 miam --export --split`

* The generated files have differences in parameters order:
```
diff --git a/6**********0-dev/roles.iam b/6**********0-dev/roles.iam
index fbffe3d..4d98567 100644
--- a/6**********0-dev/roles.iam
+++ b/6**********0-dev/roles.iam
@@ -124,9 +124,9 @@ role "ARole", :path=>"/" do
       [{"Effect"=>"Allow",
         "Principal"=>
          {"AWS"=>
-           ["arn:aws:iam::1**********0:root",
-            "arn:aws:iam::1**********1:root",
-            "arn:aws:iam::9**********6:root"]},
+           ["arn:aws:iam::1**********1:root",
+            "arn:aws:iam::9**********6:root",
+            "arn:aws:iam::1**********0:root"]},
         "Action"=>"sts:AssumeRole",
         "Condition"=>{"Bool"=>{"aws:MultiFactorAuthPresent"=>"true"}}}]}
   end
@@ -156,9 +156,9 @@ role "DRole", :path=>"/" do

   attached_managed_policies(
     "arn:aws:iam::aws:policy/AmazonEC2FullAccess",
+    "arn:aws:iam::6**********0:policy/APolicy",
     "arn:aws:iam::aws:policy/ReadOnlyAccess",
     "arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess",
-    "arn:aws:iam::6**********0:policy/APolicy",
     "arn:aws:iam::6**********0:policy/CPolicy"
   )
 end
```

Please note that:
 1. I only saw that for roles, but I've not made much tests
 1. It seems to concern both "attached_managed_policies", and the "assume_role_policy_document" JSON document.

**Comment by winebarrel** [comment]
Thank you for reporting :-)

Does the same problem occur by the latest version? (0.2.3.beta2)

**Comment by llange** [comment]
It was occurring with 0.2.3beta

It's still occurring with 0.2.3beta2 (the only difference is the OS X patch #14)

**Comment by winebarrel** [comment]
It was fixed probably. 2db27ab1bf6e8680a14e2e7b952af98e7bbb27c2
Please try [v0.2.3.beta3](https://rubygems.org/gems/miam/versions/0.2.3.beta3).

**Comment by llange** [comment]
Thanks, it looks sorted in the results now.

I will let a few days to check, but I think it should be ok.

Thanks for the quick patch.

**Comment by llange** [comment]
The order is now consistently ok.
Thanks for patching it.

**Comment by winebarrel** [comment]
:smiley:
